#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmilePlugins.Mvc.Module.PDFJS.Pages
{
    
    #line 2 "..\..\Pages\LayoutPage.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\LayoutPage.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\LayoutPage.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.Linq;
    
    #line 4 "..\..\Pages\LayoutPage.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 7 "..\..\Pages\LayoutPage.cshtml"
    using EmilePlugins.Mvc.ModuleActivator;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Pages\LayoutPage.cshtml"
    using Mvc.Module.PDFJS;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Pages\LayoutPage.cshtml"
    using Mvc.Module.PDFJS.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class LayoutPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");








WriteLiteral("\r\n");


WriteLiteral("<!DOCTYPE html>\r\n<html lang=\"");


            
            #line 12 "..\..\Pages\LayoutPage.cshtml"
       Write(CultureInfo.CurrentUICulture.TwoLetterISOLanguageName);

            
            #line default
            #line hidden
WriteLiteral(@""" dir=""ltr"" mozdisallowselectionprint moznomarginboxes>
<head>
    <meta http-equiv=""Content-Type"" content=""text/html"" >
    <meta charset=""utf-8"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1, maximum-scale=1"">
    <meta name=""google"" content=""notranslate"">
    <title>");


            
            #line 18 "..\..\Pages\LayoutPage.cshtml"
      Write(Title);

            
            #line default
            #line hidden
WriteLiteral(" - 预览</title>\r\n</head>\r\n    <body tabindex=\"1\" class=\"loadingInProgress\">\r\n      " +
"  <!-- Wrap all page content here -->\r\n        ");


            
            #line 22 "..\..\Pages\LayoutPage.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    </body>\r\n</html>\r\n\r\n\r\n \r\n");


        }
    }
}
#pragma warning restore 1591
