#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmilePlugins.Mvc.Module.PDFJS.Pages
{
    
    #line 2 "..\..\Pages\ViewStream.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\ViewStream.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    
    #line 6 "..\..\Pages\ViewStream.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 4 "..\..\Pages\ViewStream.cshtml"
    using EmilePlugins.Mvc.ModuleActivator;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Pages\ViewStream.cshtml"
    using Mvc.Module.Pdfjs;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\ViewStream.cshtml"
    using Mvc.Module.Pdfjs.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ViewStream : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







WriteLiteral("\r\n");



            
            #line 10 "..\..\Pages\ViewStream.cshtml"
  
    var Title = this.Query("name");
    var StreamUrl = this.Query("stream");
    var version = GetType().GetTypeInfo().Assembly.GetName().Version;
    Layout = new LayoutPage(Title);


            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n<link rel=\"stylesheet\" href=\"");


            
            #line 68 "..\..\Pages\ViewStream.cshtml"
                        Write(Url.To($"/css{version.Major}{version.Minor}{version.Build}"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n<script src=\"");


            
            #line 69 "..\..\Pages\ViewStream.cshtml"
        Write(Url.To($"/js/compatibility"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n\r\n<!-- This snippet is used in production (included from viewer.html" +
") -->\r\n<link rel=\"resource\" type=\"application/l10n\" href=\"");


            
            #line 72 "..\..\Pages\ViewStream.cshtml"
                                               Write($"/{Resource.Setting.ModuleName}/");

            
            #line default
            #line hidden
WriteLiteral("locale/locale/properties\" />\r\n<script src=\"");


            
            #line 73 "..\..\Pages\ViewStream.cshtml"
        Write(Url.To($"/js/l10n"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n<script src=\"");


            
            #line 74 "..\..\Pages\ViewStream.cshtml"
        Write(Url.To($"/js/pdf{version.Major}{version.Minor}{version.Build}"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n<script src=\"");


            
            #line 75 "..\..\Pages\ViewStream.cshtml"
        Write(Url.To($"/js/debugger"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n<script src=\"");


            
            #line 76 "..\..\Pages\ViewStream.cshtml"
        Write(Url.To($"/js/viewer"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n<script src=\"");


            
            #line 77 "..\..\Pages\ViewStream.cshtml"
        Write(Url.To($"/js/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n\r\n<div id=\"outerContainer\">\r\n    <div id=\"sidebarContainer\">\r\n      " +
"  <div id=\"toolbarSidebar\">\r\n            <div class=\"splitToolbarButton toggled\"" +
">\r\n                <button id=\"viewThumbnail\" class=\"toolbarButton group toggled" +
"\" title=\"Show Thumbnails\" tabindex=\"2\" data-l10n-id=\"thumbs\">\r\n                 " +
"   <span data-l10n-id=\"thumbs_label\">Thumbnails</span>\r\n                </button" +
">\r\n                <button id=\"viewOutline\" class=\"toolbarButton group\" title=\"S" +
"how Document Outline\" tabindex=\"3\" data-l10n-id=\"outline\">\r\n                    " +
"<span data-l10n-id=\"outline_label\">Document Outline</span>\r\n                </bu" +
"tton>\r\n                <button id=\"viewAttachments\" class=\"toolbarButton group\" " +
"title=\"Show Attachments\" tabindex=\"4\" data-l10n-id=\"attachments\">\r\n             " +
"       <span data-l10n-id=\"attachments_label\">Attachments</span>\r\n              " +
"  </button>\r\n            </div>\r\n        </div>\r\n        <div id=\"sidebarContent" +
"\">\r\n            <div id=\"thumbnailView\">\r\n            </div>\r\n            <div i" +
"d=\"outlineView\" class=\"hidden\">\r\n            </div>\r\n            <div id=\"attach" +
"mentsView\" class=\"hidden\">\r\n            </div>\r\n        </div>\r\n    </div>  <!--" +
" sidebarContainer -->\r\n    <div id=\"mainContainer\">\r\n\r\n        <div class=\"findb" +
"ar hidden doorHanger hiddenSmallView\" id=\"findbar\">\r\n            <label for=\"fin" +
"dInput\" class=\"toolbarLabel\" data-l10n-id=\"find_label\">Find:</label>\r\n          " +
"  <input id=\"findInput\" class=\"toolbarField\" tabindex=\"91\">\r\n            <div cl" +
"ass=\"splitToolbarButton\">\r\n                <button class=\"toolbarButton findPrev" +
"ious\" title=\"\" id=\"findPrevious\" tabindex=\"92\" data-l10n-id=\"find_previous\">\r\n  " +
"                  <span data-l10n-id=\"find_previous_label\">Previous</span>\r\n    " +
"            </button>\r\n                <div class=\"splitToolbarButtonSeparator\">" +
"</div>\r\n                <button class=\"toolbarButton findNext\" title=\"\" id=\"find" +
"Next\" tabindex=\"93\" data-l10n-id=\"find_next\">\r\n                    <span data-l1" +
"0n-id=\"find_next_label\">Next</span>\r\n                </button>\r\n            </di" +
"v>\r\n            <input type=\"checkbox\" id=\"findHighlightAll\" class=\"toolbarField" +
"\">\r\n            <label for=\"findHighlightAll\" class=\"toolbarLabel\" tabindex=\"94\"" +
" data-l10n-id=\"find_highlight\">Highlight all</label>\r\n            <input type=\"c" +
"heckbox\" id=\"findMatchCase\" class=\"toolbarField\">\r\n            <label for=\"findM" +
"atchCase\" class=\"toolbarLabel\" tabindex=\"95\" data-l10n-id=\"find_match_case_label" +
"\">Match case</label>\r\n            <span id=\"findMsg\" class=\"toolbarLabel\"></span" +
">\r\n        </div>  <!-- findbar -->\r\n\r\n        <div id=\"secondaryToolbar\" class=" +
"\"secondaryToolbar hidden doorHangerRight\">\r\n            <div id=\"secondaryToolba" +
"rButtonContainer\">\r\n                <button id=\"secondaryPresentationMode\" class" +
"=\"secondaryToolbarButton presentationMode visibleLargeView\" title=\"Switch to Pre" +
"sentation Mode\" tabindex=\"51\" data-l10n-id=\"presentation_mode\">\r\n               " +
"     <span data-l10n-id=\"presentation_mode_label\">Presentation Mode</span>\r\n    " +
"            </button>\r\n                <button id=\"secondaryOpenFile\" class=\"sec" +
"ondaryToolbarButton openFile visibleLargeView\" title=\"Open File\" tabindex=\"52\" d" +
"ata-l10n-id=\"open_file\">\r\n                    <span data-l10n-id=\"open_file_labe" +
"l\">Open</span>\r\n                </button>\r\n                <button id=\"secondary" +
"Print\" class=\"secondaryToolbarButton print visibleMediumView\" title=\"Print\" tabi" +
"ndex=\"53\" data-l10n-id=\"print\">\r\n                    <span data-l10n-id=\"print_l" +
"abel\">Print</span>\r\n                </button>\r\n                <button id=\"secon" +
"daryDownload\" class=\"secondaryToolbarButton download visibleMediumView\" title=\"D" +
"ownload\" tabindex=\"54\" data-l10n-id=\"download\">\r\n                    <span data-" +
"l10n-id=\"download_label\">Download</span>\r\n                </button>\r\n           " +
"     <a href=\"#\" id=\"secondaryViewBookmark\" class=\"secondaryToolbarButton bookma" +
"rk visibleSmallView\" title=\"Current view (copy or open in new window)\" tabindex=" +
"\"55\" data-l10n-id=\"bookmark\">\r\n                    <span data-l10n-id=\"bookmark_" +
"label\">Current View</span>\r\n                </a>\r\n                <div class=\"ho" +
"rizontalToolbarSeparator visibleLargeView\"></div>\r\n                <button id=\"f" +
"irstPage\" class=\"secondaryToolbarButton firstPage\" title=\"Go to First Page\" tabi" +
"ndex=\"56\" data-l10n-id=\"first_page\">\r\n                    <span data-l10n-id=\"fi" +
"rst_page_label\">Go to First Page</span>\r\n                </button>\r\n            " +
"    <button id=\"lastPage\" class=\"secondaryToolbarButton lastPage\" title=\"Go to L" +
"ast Page\" tabindex=\"57\" data-l10n-id=\"last_page\">\r\n                    <span dat" +
"a-l10n-id=\"last_page_label\">Go to Last Page</span>\r\n                </button>\r\n " +
"               <div class=\"horizontalToolbarSeparator\"></div>\r\n                <" +
"button id=\"pageRotateCw\" class=\"secondaryToolbarButton rotateCw\" title=\"Rotate C" +
"lockwise\" tabindex=\"58\" data-l10n-id=\"page_rotate_cw\">\r\n                    <spa" +
"n data-l10n-id=\"page_rotate_cw_label\">Rotate Clockwise</span>\r\n                <" +
"/button>\r\n                <button id=\"pageRotateCcw\" class=\"secondaryToolbarButt" +
"on rotateCcw\" title=\"Rotate Counterclockwise\" tabindex=\"59\" data-l10n-id=\"page_r" +
"otate_ccw\">\r\n                    <span data-l10n-id=\"page_rotate_ccw_label\">Rota" +
"te Counterclockwise</span>\r\n                </button>\r\n                <div clas" +
"s=\"horizontalToolbarSeparator\"></div>\r\n                <button id=\"toggleHandToo" +
"l\" class=\"secondaryToolbarButton handTool\" title=\"Enable hand tool\" tabindex=\"60" +
"\" data-l10n-id=\"hand_tool_enable\">\r\n                    <span data-l10n-id=\"hand" +
"_tool_enable_label\">Enable hand tool</span>\r\n                </button>\r\n\r\n      " +
"          <div class=\"horizontalToolbarSeparator\"></div>\r\n                <butto" +
"n id=\"documentProperties\" class=\"secondaryToolbarButton documentProperties\" titl" +
"e=\"Document Properties…\" tabindex=\"61\" data-l10n-id=\"document_properties\">\r\n    " +
"                <span data-l10n-id=\"document_properties_label\">Document Properti" +
"es…</span>\r\n                </button>\r\n            </div>\r\n        </div>  <!-- " +
"secondaryToolbar -->\r\n\r\n        <div class=\"toolbar\">\r\n            <div id=\"tool" +
"barContainer\">\r\n                <div id=\"toolbarViewer\">\r\n                    <d" +
"iv id=\"toolbarViewerLeft\">\r\n                        <button id=\"sidebarToggle\" c" +
"lass=\"toolbarButton\" title=\"Toggle Sidebar\" tabindex=\"11\" data-l10n-id=\"toggle_s" +
"idebar\">\r\n                            <span data-l10n-id=\"toggle_sidebar_label\">" +
"Toggle Sidebar</span>\r\n                        </button>\r\n                      " +
"  <div class=\"toolbarButtonSpacer\"></div>\r\n                        <button id=\"v" +
"iewFind\" class=\"toolbarButton group hiddenSmallView\" title=\"Find in Document\" ta" +
"bindex=\"12\" data-l10n-id=\"findbar\">\r\n                            <span data-l10n" +
"-id=\"findbar_label\">Find</span>\r\n                        </button>\r\n            " +
"            <div class=\"splitToolbarButton\">\r\n                            <butto" +
"n class=\"toolbarButton pageUp\" title=\"Previous Page\" id=\"previous\" tabindex=\"13\"" +
" data-l10n-id=\"previous\">\r\n                                <span data-l10n-id=\"p" +
"revious_label\">Previous</span>\r\n                            </button>\r\n         " +
"                   <div class=\"splitToolbarButtonSeparator\"></div>\r\n            " +
"                <button class=\"toolbarButton pageDown\" title=\"Next Page\" id=\"nex" +
"t\" tabindex=\"14\" data-l10n-id=\"next\">\r\n                                <span dat" +
"a-l10n-id=\"next_label\">Next</span>\r\n                            </button>\r\n     " +
"                   </div>\r\n                        <label id=\"pageNumberLabel\" c" +
"lass=\"toolbarLabel\" for=\"pageNumber\" data-l10n-id=\"page_label\">Page: </label>\r\n " +
"                       <input type=\"number\" id=\"pageNumber\" class=\"toolbarField " +
"pageNumber\" value=\"1\" size=\"4\" min=\"1\" tabindex=\"15\">\r\n                        <" +
"span id=\"numPages\" class=\"toolbarLabel\"></span>\r\n                    </div>\r\n\r\n " +
"                   <div id=\"toolbarViewerRight\">\r\n                        <butto" +
"n id=\"presentationMode\" class=\"toolbarButton presentationMode hiddenLargeView\" t" +
"itle=\"Switch to Presentation Mode\" tabindex=\"31\" data-l10n-id=\"presentation_mode" +
"\">\r\n                            <span data-l10n-id=\"presentation_mode_label\">Pre" +
"sentation Mode</span>\r\n                        </button>\r\n                      " +
"  <button id=\"openFile\" class=\"toolbarButton openFile hiddenLargeView\" title=\"Op" +
"en File\" tabindex=\"32\" data-l10n-id=\"open_file\">\r\n                            <s" +
"pan data-l10n-id=\"open_file_label\">Open</span>\r\n                        </button" +
">\r\n                        <button id=\"print\" class=\"toolbarButton print hiddenM" +
"ediumView\" title=\"Print\" tabindex=\"33\" data-l10n-id=\"print\">\r\n                  " +
"          <span data-l10n-id=\"print_label\">Print</span>\r\n                       " +
" </button>\r\n                        <button id=\"download\" class=\"toolbarButton d" +
"ownload hiddenMediumView\" title=\"Download\" tabindex=\"34\" data-l10n-id=\"download\"" +
">\r\n                            <span data-l10n-id=\"download_label\">Download</spa" +
"n>\r\n                        </button>\r\n                        <!-- <div class=\"" +
"toolbarButtonSpacer\"></div> -->\r\n                        <a href=\"#\" id=\"viewBoo" +
"kmark\" class=\"toolbarButton bookmark hiddenSmallView\" title=\"Current view (copy " +
"or open in new window)\" tabindex=\"35\" data-l10n-id=\"bookmark\">\r\n                " +
"            <span data-l10n-id=\"bookmark_label\">Current View</span>\r\n           " +
"             </a>\r\n                        <div class=\"verticalToolbarSeparator " +
"hiddenSmallView\"></div>\r\n\r\n                        <button id=\"secondaryToolbarT" +
"oggle\" class=\"toolbarButton\" title=\"Tools\" tabindex=\"36\" data-l10n-id=\"tools\">\r\n" +
"                            <span data-l10n-id=\"tools_label\">Tools</span>\r\n     " +
"                   </button>\r\n                    </div>\r\n\r\n                    " +
"<div class=\"outerCenter\">\r\n                        <div class=\"innerCenter\" id=\"" +
"toolbarViewerMiddle\">\r\n                            <div class=\"splitToolbarButto" +
"n\">\r\n                                <button id=\"zoomOut\" class=\"toolbarButton z" +
"oomOut\" title=\"Zoom Out\" tabindex=\"21\" data-l10n-id=\"zoom_out\">\r\n               " +
"                     <span data-l10n-id=\"zoom_out_label\">Zoom Out</span>\r\n      " +
"                          </button>\r\n                                <div class=" +
"\"splitToolbarButtonSeparator\"></div>\r\n                                <button id" +
"=\"zoomIn\" class=\"toolbarButton zoomIn\" title=\"Zoom In\" tabindex=\"22\" data-l10n-i" +
"d=\"zoom_in\">\r\n                                    <span data-l10n-id=\"zoom_in_la" +
"bel\">Zoom In</span>\r\n                                </button>\r\n                " +
"            </div>\r\n                            <span id=\"scaleSelectContainer\" " +
"class=\"dropdownToolbarButton\">\r\n                                <select id=\"scal" +
"eSelect\" title=\"Zoom\" tabindex=\"23\" data-l10n-id=\"zoom\">\r\n                      " +
"              <option id=\"pageAutoOption\" title=\"\" value=\"auto\" selected=\"select" +
"ed\" data-l10n-id=\"page_scale_auto\">Automatic Zoom</option>\r\n                    " +
"                <option id=\"pageActualOption\" title=\"\" value=\"page-actual\" data-" +
"l10n-id=\"page_scale_actual\">Actual Size</option>\r\n                              " +
"      <option id=\"pageFitOption\" title=\"\" value=\"page-fit\" data-l10n-id=\"page_sc" +
"ale_fit\">Fit Page</option>\r\n                                    <option id=\"page" +
"WidthOption\" title=\"\" value=\"page-width\" data-l10n-id=\"page_scale_width\">Full Wi" +
"dth</option>\r\n                                    <option id=\"customScaleOption\"" +
" title=\"\" value=\"custom\"></option>\r\n                                    <option " +
"title=\"\" value=\"0.5\">50%</option>\r\n                                    <option t" +
"itle=\"\" value=\"0.75\">75%</option>\r\n                                    <option t" +
"itle=\"\" value=\"1\">100%</option>\r\n                                    <option tit" +
"le=\"\" value=\"1.25\">125%</option>\r\n                                    <option ti" +
"tle=\"\" value=\"1.5\">150%</option>\r\n                                    <option ti" +
"tle=\"\" value=\"2\">200%</option>\r\n                                    <option titl" +
"e=\"\" value=\"3\">300%</option>\r\n                                    <option title=" +
"\"\" value=\"4\">400%</option>\r\n                                </select>\r\n         " +
"                   </span>\r\n                        </div>\r\n                    " +
"</div>\r\n\r\n                </div>\r\n                <div id=\"loadingBar\">\r\n       " +
"             <div class=\"progress\">\r\n                        <div class=\"glimmer" +
"\">\r\n                        </div>\r\n                    </div>\r\n                " +
"</div>\r\n            </div>\r\n        </div>\r\n\r\n        <menu type=\"context\" id=\"v" +
"iewerContextMenu\">\r\n            <menuitem id=\"contextFirstPage\" label=\"First Pag" +
"e\"\r\n                      data-l10n-id=\"first_page\"></menuitem>\r\n            <me" +
"nuitem id=\"contextLastPage\" label=\"Last Page\"\r\n                      data-l10n-i" +
"d=\"last_page\"></menuitem>\r\n            <menuitem id=\"contextPageRotateCw\" label=" +
"\"Rotate Clockwise\"\r\n                      data-l10n-id=\"page_rotate_cw\"></menuit" +
"em>\r\n            <menuitem id=\"contextPageRotateCcw\" label=\"Rotate Counter-Clock" +
"wise\"\r\n                      data-l10n-id=\"page_rotate_ccw\"></menuitem>\r\n       " +
" </menu>\r\n\r\n        <div id=\"viewerContainer\" tabindex=\"0\">\r\n            <div id" +
"=\"viewer\"></div>\r\n        </div>\r\n\r\n        <div id=\"errorWrapper\" hidden=\'true\'" +
">\r\n            <div id=\"errorMessageLeft\">\r\n                <span id=\"errorMessa" +
"ge\"></span>\r\n                <button id=\"errorShowMore\" data-l10n-id=\"error_more" +
"_info\">\r\n                    More Information\r\n                </button>\r\n      " +
"          <button id=\"errorShowLess\" data-l10n-id=\"error_less_info\" hidden=\'true" +
"\'>\r\n                    Less Information\r\n                </button>\r\n           " +
" </div>\r\n            <div id=\"errorMessageRight\">\r\n                <button id=\"e" +
"rrorClose\" data-l10n-id=\"error_close\">\r\n                    Close\r\n             " +
"   </button>\r\n            </div>\r\n            <div class=\"clearBoth\"></div>\r\n   " +
"         <textarea id=\"errorMoreInfo\" hidden=\'true\' readonly=\"readonly\"></textar" +
"ea>\r\n        </div>\r\n    </div> <!-- mainContainer -->\r\n\r\n    <div id=\"overlayCo" +
"ntainer\" class=\"hidden\">\r\n        <div id=\"passwordOverlay\" class=\"container hid" +
"den\">\r\n            <div class=\"dialog\">\r\n                <div class=\"row\">\r\n    " +
"                <p id=\"passwordText\" data-l10n-id=\"password_label\">Enter the pas" +
"sword to open this PDF file:</p>\r\n                </div>\r\n                <div c" +
"lass=\"row\">\r\n                    <input type=\"password\" id=\"password\" class=\"too" +
"lbarField\" />\r\n                </div>\r\n                <div class=\"buttonRow\">\r\n" +
"                    <button id=\"passwordCancel\" class=\"overlayButton\"><span data" +
"-l10n-id=\"password_cancel\">Cancel</span></button>\r\n                    <button i" +
"d=\"passwordSubmit\" class=\"overlayButton\"><span data-l10n-id=\"password_ok\">OK</sp" +
"an></button>\r\n                </div>\r\n            </div>\r\n        </div>\r\n\r\n    " +
"    <div id=\"documentPropertiesOverlay\" class=\"container hidden\">\r\n            <" +
"div class=\"dialog\">\r\n                <div class=\"row\">\r\n                    <spa" +
"n data-l10n-id=\"document_properties_file_name\">File name:</span> <p id=\"fileName" +
"Field\">-</p>\r\n                </div>\r\n                <div class=\"row\">\r\n       " +
"             <span data-l10n-id=\"document_properties_file_size\">File size:</span" +
"> <p id=\"fileSizeField\">-</p>\r\n                </div>\r\n                <div clas" +
"s=\"separator\"></div>\r\n                <div class=\"row\">\r\n                    <sp" +
"an data-l10n-id=\"document_properties_title\">Title:</span> <p id=\"titleField\">-</" +
"p>\r\n                </div>\r\n                <div class=\"row\">\r\n                 " +
"   <span data-l10n-id=\"document_properties_author\">Author:</span> <p id=\"authorF" +
"ield\">-</p>\r\n                </div>\r\n                <div class=\"row\">\r\n        " +
"            <span data-l10n-id=\"document_properties_subject\">Subject:</span> <p " +
"id=\"subjectField\">-</p>\r\n                </div>\r\n                <div class=\"row" +
"\">\r\n                    <span data-l10n-id=\"document_properties_keywords\">Keywor" +
"ds:</span> <p id=\"keywordsField\">-</p>\r\n                </div>\r\n                " +
"<div class=\"row\">\r\n                    <span data-l10n-id=\"document_properties_c" +
"reation_date\">Creation Date:</span> <p id=\"creationDateField\">-</p>\r\n           " +
"     </div>\r\n                <div class=\"row\">\r\n                    <span data-l" +
"10n-id=\"document_properties_modification_date\">Modification Date:</span> <p id=\"" +
"modificationDateField\">-</p>\r\n                </div>\r\n                <div class" +
"=\"row\">\r\n                    <span data-l10n-id=\"document_properties_creator\">Cr" +
"eator:</span> <p id=\"creatorField\">-</p>\r\n                </div>\r\n              " +
"  <div class=\"separator\"></div>\r\n                <div class=\"row\">\r\n            " +
"        <span data-l10n-id=\"document_properties_producer\">PDF Producer:</span> <" +
"p id=\"producerField\">-</p>\r\n                </div>\r\n                <div class=\"" +
"row\">\r\n                    <span data-l10n-id=\"document_properties_version\">PDF " +
"Version:</span> <p id=\"versionField\">-</p>\r\n                </div>\r\n            " +
"    <div class=\"row\">\r\n                    <span data-l10n-id=\"document_properti" +
"es_page_count\">Page Count:</span> <p id=\"pageCountField\">-</p>\r\n                " +
"</div>\r\n                <div class=\"buttonRow\">\r\n                    <button id=" +
"\"documentPropertiesClose\" class=\"overlayButton\"><span data-l10n-id=\"document_pro" +
"perties_close\">Close</span></button>\r\n                </div>\r\n            </div>" +
"\r\n        </div>\r\n\r\n    </div>  <!-- overlayContainer -->\r\n\r\n</div> <!-- outerCo" +
"ntainer -->\r\n\r\n<div id=\"printContainer\"></div>\r\n\r\n<div id=\"mozPrintCallback-shim" +
"\" hidden>\r\n    <style scoped>\r\n        #mozPrintCallback-shim {\r\n            pos" +
"ition: fixed;\r\n            top: 0;\r\n            left: 0;\r\n            height: 10" +
"0%;\r\n            width: 100%;\r\n            z-index: 9999999;\r\n            displa" +
"y: block;\r\n            text-align: center;\r\n            background-color: rgba(0" +
", 0, 0, 0.5);\r\n        }\r\n\r\n            #mozPrintCallback-shim[hidden] {\r\n      " +
"          display: none;\r\n            }\r\n\r\n        ");


WriteLiteral("@media print {\r\n            #mozPrintCallback-shim {\r\n                display: no" +
"ne;\r\n            }\r\n        }\r\n\r\n        #mozPrintCallback-shim .mozPrintCallbac" +
"k-dialog-box {\r\n            display: inline-block;\r\n            margin: -50px au" +
"to 0;\r\n            position: relative;\r\n            top: 45%;\r\n            left:" +
" 0;\r\n            min-width: 220px;\r\n            max-width: 400px;\r\n            p" +
"adding: 9px;\r\n            border: 1px solid hsla(0, 0%, 0%, .5);\r\n            bo" +
"rder-radius: 2px;\r\n            box-shadow: 0 1px 4px rgba(0, 0, 0, 0.3);\r\n      " +
"      background-color: #474747;\r\n            color: hsl(0, 0%, 85%);\r\n         " +
"   font-size: 16px;\r\n            line-height: 20px;\r\n        }\r\n\r\n        #mozPr" +
"intCallback-shim .progress-row {\r\n            clear: both;\r\n            padding:" +
" 1em 0;\r\n        }\r\n\r\n        #mozPrintCallback-shim progress {\r\n            wid" +
"th: 100%;\r\n        }\r\n\r\n        #mozPrintCallback-shim .relative-progress {\r\n   " +
"         clear: both;\r\n            float: right;\r\n        }\r\n\r\n        #mozPrint" +
"Callback-shim .progress-actions {\r\n            clear: both;\r\n        }\r\n    </st" +
"yle>\r\n    <div class=\"mozPrintCallback-dialog-box\">\r\n        <!-- TODO: Localise" +
" the following strings -->\r\n        Preparing document for printing...\r\n        " +
"<div class=\"progress-row\">\r\n            <progress value=\"0\" max=\"100\"></progress" +
">\r\n            <span class=\"relative-progress\">0%</span>\r\n        </div>\r\n      " +
"  <div class=\"progress-actions\">\r\n            <input type=\"button\" value=\"Cancel" +
"\" class=\"mozPrintCallback-cancel\">\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<scrip" +
"t>\r\n    DEFAULT_URL = \"\";\r\n    if (\"");


            
            #line 435 "..\..\Pages\ViewStream.cshtml"
    Write(StreamUrl);

            
            #line default
            #line hidden
WriteLiteral("\" != \"\") {\r\n        $.ajax({\r\n            type: \"get\",\r\n            async: false," +
"\r\n            mimeType: \'text/plain; charset=x-user-defined\',\r\n            url: " +
"\'");


            
            #line 440 "..\..\Pages\ViewStream.cshtml"
             Write(StreamUrl);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            success: function (data) {\r\n                PDFJS.imageResourcesP" +
"ath = \'/images/\';\r\n                PDFJS.workerSrc = \'/");


            
            #line 443 "..\..\Pages\ViewStream.cshtml"
                               Write(Resource.Setting.ModuleName);

            
            #line default
            #line hidden
WriteLiteral(@"/js/pdfworker';
                PDFJS.cMapUrl = '/cmaps/';
                PDFJS.cMapPacked = true;

                var PDFData = data;

                var rawLength = PDFData.length;
                //转换成pdf.js能直接解析的Uint8Array类型,见pdf.js-4068
                var array = new Uint8Array(new ArrayBuffer(rawLength));
                for (i = 0; i < rawLength; i++) {
                    array[i] = PDFData.charCodeAt(i) & 0xff;
                }
                DEFAULT_URL = array;
            }
        });
    }

</script>
");


        }
    }
}
#pragma warning restore 1591
